#!/bin/bash

# allocate swapfile (see: https://github.com/rails/rails-dev-box/pull/108)
if [[ ! -e /swapfile ]]; then
  sudo fallocate -l 2G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  sudo sh -c "echo '/swapfile none swap defaults 0 0' >> /etc/fstab"
fi

# git directory
mkdir -p ~/git
cd ~/git

# clone awdwr into the git directory
if [[ ! -e ~/git/awdwr ]]; then
  git clone https://github.com/rubys/awdwr.git
fi

cd awdwr

bash_reload=false

# testrails alias
if ! grep -q 'alias testrails=' ~/.bashrc ; then
  echo "alias testrails='ruby `pwd`/testrails.rb'" >> ~/.bashrc
  bash_reload=true
fi

# work alias
if ! grep -q 'alias work=' ~/.bashrc ; then
  echo "alias work='source `pwd`/vagrant/bin/work'" >> ~/.bashrc
  bash_reload=true
fi

# depot alias
if ! grep -q 'alias depot=' ~/.bashrc ; then
  echo "alias depot='bash `pwd`/vagrant/bin/depot'" >> ~/.bashrc
  bash_reload=true
fi

# dashboard port
if ! grep -q 'export PORT=' ~/.bashrc ; then
  echo "export PORT=3000" >> ~/.bashrc
  bash_reload=true
fi

# dashboard ip
if ! grep -q 'export IP=' ~/.bashrc ; then
  echo "export IP=0.0.0.0" >> ~/.bashrc
  bash_reload=true
fi

# reload bash if needed
if [ "$bash_reload" = true ] ; then
  source ~/.bashrc
fi

# run setup
if [[ ! -e ~/git/gorp ]]; then
  ruby setup.rb
fi

# install gems
if [[ ! -e  Gemfile.lock ]]; then
  bundle update
fi
