#!/bin/bash

# git directory
mkdir -p ~/git
cd ~/git

# rvm
if ! grep -q 'rvm' ~/.bashrc ; then
  echo "source  /usr/local/rvm/scripts/rvm" >> ~/.bashrc
fi

# sync aliases
if ! grep -q 'alias sync-' ~/.bashrc ; then
  echo "alias sync-in='rsync -av --delete --exclude AWDwR4 --exclude \"edition4/work*\" --exclude edition4/snapshot --exclude \"edition3/work*\" --exclude edition3/snapshot /srv/awdwr/ /home/awdwr/git/awdwr/'" >> ~/.bashrc
  echo "alias sync-out='rsync -av /home/awdwr/git/awdwr/ /srv/awdwr'" >> ~/.bashrc
  bash_reload=true
fi

# clone awdwr into the git directory; create work directory
if [[ ! -e ~/git/awdwr ]]; then
  git clone https://github.com/rubys/awdwr.git
  mkdir -p awdwr/edition4/work
fi

cd -

# install shotgun
if ! [ -x "$(command -v shotgun)" ]; then
  gem install shotgun
fi

# common setup
export MYSQL_HOST=awdwr-mysql
source './common-setup'
